{
  "name": "Seplos3MQTT",
  "version": "1.0",
  "slug": "seplos3mqtt",
  "description": "Add-on for Seplos3MQTT integration",
  "arch": ["amd64", "armhf", "armv7", "aarch64"],
  "startup": "services",
  "boot": "auto",
  "host": "host.docker.internal",
  "ports": {
    "1883/tcp": 1883
  },
  "services": [
    {
      "name": "seplos3mqtt",
      "port": 1883
    }
  ],
  "options": {
    "mqtt_broker": "mqtt://192.168.1.110",
    "mqtt_port": 1883
    "mqtt_user": "seplos",
    "mqtt_password": "seplosbms"
  }
}
