version: "3"
services:
  homeassistant:
    container_name: seplos
    image: seplos3mqtt
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - serial=/dev/ttyUSB0
      - mqtt_server=192.168.1.110
      - mqtt_user=energy
      - mqtt_pass=Energy25!
